sudo: required
services:
  - docker 
  
before_install:
  # Initila image 
  - docker build -t mhd/docker-react -f Dockerfile.dev .

# travis CI will be watching the output of this commands 
# if it returns  an output =! 0,  travis CI will assume that 
# our code is broken 
script:
  - docker run mhd/docker-react npm run test -- --coverage

# Deploy the application in aws 
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  # ( bucket where to pu the zip file to deploy the application )
  # hard drive running on aws  ( Data Lake ) 
  bucket_name: "elasticbeanstalk-us-east-2-862306857326"  
  bucket_path: "docker-react"
  on:
    branch: master 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
